### ISSUE TITLE
Blog about release of 1.30.2

### ISSUE THREAD

**Issue by mnoorenberghe** [ZoneMinder/zoneminder.github.io#13]
To make the project/site seem alive I would recommend copying the release notes of 1.30.2 to the blog to announce it there.

I'll do the work if nobody else wants to do it but I wanted to get confirmation that it would be wanted before spending time on it.

**Comment by mnoorenberghe** [comment]
I guess the announcement forum should also be updated: https://forums.zoneminder.com/viewforum.php?f=1

**Comment by knight-of-ni** [comment]
You're absolutely right. I'm usually buried knee deep in some technical problem that I never take the time to do anything else, like make announcements. This week though, I'm out of town, so I'm hoping one of the other guys on the team can take of this one.

**Comment by hutchic** [comment]
now that `1.30.4` has landed (and has a blog post) is there any reason to create a blog post for `1.30.2` and if there's not this issue can probably be closed IMO
