### ISSUE TITLE
firefox on ubuntu not load all monitors in montage view

### ISSUE THREAD

**Issue by saqibgilani79** [ZoneMinder/zoneminder.github.io#19]
Good day,

I am facing this problem from day one after installation, I installed from source version 13.0.2.
I installed 12 cameras on zoneminder, montage review showing complete monitors but when i open montage view its showing only 6 cameras .. rest of all blank

second important thing, I need your help for outdoor camera settings, I installed 4 outdoor cameras but i failed to configure light effect issue, cameras generate false alarm on day night change.
I will be very grateful for your kind help.
Please advise .

Rgrds,

**Comment by SteveGilvarry** [comment]
Wrong project, this is www.zoneminder.com website not the application. If you had posted there you would have seen a request that all usage questions should be directed to forums.zoneminder.com, that second question will have already been answered there. Your first question is in the FAQ.
http://zoneminder.readthedocs.io/en/stable/faq.html#i-have-several-monitors-configured-but-when-i-load-the-montage-view-in-firefox-why-can-i-only-see-two-or-why-don-t-all-my-cameras-display-when-i-use-the-montage-view-in-firefox
