### ISSUE TITLE
Incorrect version of the Fedora logo used

### ISSUE THREAD

**Issue by justwheel** [ZoneMinder/zoneminder.github.io#20]
Hello,

Just a quick note about the [RedFedCent.png](https://github.com/ZoneMinder/zoneminder.github.io/blob/master/images/RedFedCent.png) image used for Red Hat, Fedora, and CentOS downloads. The Fedora logo used is one that doesn't adhere to the Fedora logo standards (we've slowly been trying to get this specific version out of use where possible). 😁 

It would be great if a new version could be created with the official logo that adheres to the styling guidelines. Both a SVG and PNG versions can be downloaded from the [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Fedora_logo.svg).

Thanks!

**Comment by knight-of-ni** [comment]
@kylejohnson Did you create the mentioned RedFedCent image yourself or did you download that from somewhere?

**Comment by justwheel** [comment]
@knight-of-ni Cool, thanks for the fix! :+1:
